Extracci√≥n

In [3]:
import pandas as pd
import numpy as np

In [4]:
url = 'https://raw.githubusercontent.com/ronalcabrera/PG_Olist/main/Datasets/olist_closed_deals_dataset.csv'

df_closed_deals = pd.read_csv(url, delimiter=',', encoding='UTF-8')

In [5]:
df_closed_deals.sample(5)

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
211,667f061b738858573caad66f5cc56b32,96c1c7f1f24470915da80563cd1202ea,e7dff61b78bebffa71678e126ce669ad,d3d1e91a157ea7f90548eef82f1955e3,2018-08-08 16:22:31,audio_video_electronics,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0
34,72e81de94dfc0373b006ca75e9c851a1,2f1e89e231b096f4ff1f55dfe8607a7b,e7dff61b78bebffa71678e126ce669ad,068066e24f0c643eb1d089c7dd20cd73,2018-10-31 16:54:59,computers,online_medium,cat,True,NaN,1-5,reseller,80.0,0.0
583,d75057842b733134576d690d1d9509a2,a86bf7a9ba609d0527f10ea8f0a5446c,f42a2bd194f7802ab052a815c8de65b7,6565aa9ce3178a5caf6171827af3a9ba,2018-05-08 20:14:11,sports_leisure,offline,eagle,NaN,NaN,NaN,manufacturer,NaN,0.0
323,19c777b5bed02ee09375ce374cf653f1,13a6bea45beacabbd2d7551940020653,09285259593c61296eef10c734121d5b,6565aa9ce3178a5caf6171827af3a9ba,2018-04-18 16:36:44,construction_tools_house_garden,online_medium,cat,NaN,NaN,NaN,manufacturer,NaN,0.0
8,a90a37898cc5f2718385a2fb981caaff,0b28859cd04d23edefee9c591fb03cd8,f42a2bd194f7802ab052a815c8de65b7,6565aa9ce3178a5caf6171827af3a9ba,2018-05-14 18:37:15,household_utilities,offline,eagle,NaN,NaN,NaN,reseller,NaN,0.0

In [6]:
# Tipo de datos de cada columna 
df_closed_deals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   mql_id                         842 non-null    object
 1   seller_id                      842 non-null    object
 2   sdr_id                         842 non-null    object
 3   sr_id                          842 non-null    object
 4   won_date                       842 non-null    object
 5   business_segment               841 non-null    object
 6   lead_type                      836 non-null    object
 7   lead_behaviour_profile         665 non-null    object
 8   has_company                    63 non-null     object
 9   has_gtin                       64 non-null     object
 10  average_stock                  66 non-null     object
 11  business_type                  832 non-null    object
 12  declared_product_catalog_size  69 non-null     float64
 13  declared_monthly_revenue       842 non-null    float64
dtypes: float64(2), object(12)
memory usage: 92.2+ KB

In [7]:
# Verificamos cantidad de nulos por columna

df_closed_deals.isnull().sum()

mql_id                             0
seller_id                          0
sdr_id                             0
sr_id                              0
won_date                           0
business_segment                   1
lead_type                          6
lead_behaviour_profile           177
has_company                      779
has_gtin                         778
average_stock                    776
business_type                     10
declared_product_catalog_size    773
declared_monthly_revenue           0
dtype: int64

In [8]:
df_closed_deals.drop_duplicates() # No hay duplicados

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
0,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0
1,a555fb36b9368110ede0f043dfc3b9a0,bbb7d7893a450660432ea6652310ebb7,09285259593c61296eef10c734121d5b,d3d1e91a157ea7f90548eef82f1955e3,2018-05-08 20:17:59,car_accessories,industry,eagle,NaN,NaN,NaN,reseller,NaN,0.0
2,327174d3648a2d047e8940d7d15204ca,612170e34b97004b3ba37eae81836b4c,b90f87164b5f8c2cfa5c8572834dbe3f,6565aa9ce3178a5caf6171827af3a9ba,2018-06-05 17:27:23,home_appliances,online_big,cat,NaN,NaN,NaN,reseller,NaN,0.0
3,f5fee8f7da74f4887f5bcae2bafb6dd6,21e1781e36faf92725dde4730a88ca0f,56bf83c4bb35763a51c2baab501b4c67,d3d1e91a157ea7f90548eef82f1955e3,2018-01-17 13:51:03,food_drink,online_small,NaN,NaN,NaN,NaN,reseller,NaN,0.0
4,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,2018-07-03 20:17:45,home_appliances,industry,wolf,NaN,NaN,NaN,manufacturer,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,df9a2abe2ad3f2d8758b675ac8331ecf,bfcc27719640628da877db48b672b169,45749fb708130f78d0db07d8d80f030b,a8387c01a09e99ce014107505b92388c,2018-08-01 20:22:31,home_decor,offline,cat,NaN,NaN,NaN,reseller,NaN,0.0
838,8723201570415eb23b4f095d8c20a27c,4a82eab98441aeb64566e2776c1fb2b6,370c9f455f93a9a96cbe9bea48e70033,4b339f9567d060bcea4f5136b9f5949e,2018-09-27 18:58:41,construction_tools_house_garden,online_big,wolf,NaN,NaN,NaN,reseller,132.0,200000.0
839,2e57665b8faf05c967a801eb5aedfa0a,55031883943971ca22db6894574cfe2c,370c9f455f93a9a96cbe9bea48e70033,a8387c01a09e99ce014107505b92388c,2018-06-06 20:15:26,computers,online_medium,wolf,NaN,NaN,NaN,reseller,NaN,0.0
840,40955be51cc85c5a5a6cdd12b19e9f10,c0e933c238e41f0cd459d6025ee9b364,068066e24f0c643eb1d089c7dd20cd73,d3d1e91a157ea7f90548eef82f1955e3,2018-03-06 15:52:23,pet,online_beginner,cat,NaN,NaN,NaN,reseller,NaN,0.0
841,8a6492305a5fbcdcdd1a7f5a90764c07,1bba9c94eb5c4e82fba9f7286fe81025,56bf83c4bb35763a51c2baab501b4c67,de63de0d10a6012430098db33c679b0b,2018-05-02 13:31:32,household_utilities,industry,eagle,NaN,NaN,NaN,manufacturer,NaN,0.0

In [9]:
# Cambiar la columna won_date a tipo datetime
df_closed_deals['won_date'] = pd.to_datetime(df_closed_deals['won_date'])

In [10]:
df_closed_deals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   mql_id                         842 non-null    object
 1   seller_id                      842 non-null    object
 2   sdr_id                         842 non-null    object
 3   sr_id                          842 non-null    object
 4   won_date                       842 non-null    datetime64[ns]
 5   business_segment               841 non-null    object
 6   lead_type                      836 non-null    object
 7   lead_behaviour_profile         665 non-null    object
 8   has_company                    63 non-null     object
 9   has_gtin                       64 non-null     object
 10  average_stock                  66 non-null     object
 11  business_type                  832 non-null    object
 12  declared_product_catalog_size  69 non-null     float64
 13  declared_monthly_revenue       842 non-null    float64
dtypes: datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ KB

In [11]:
# Verificamos valores unicos para encontrar redacciones err√≥neas y repararlas

print(df_closed_deals["business_segment"].unique())
print(df_closed_deals["lead_type"].unique())
print(df_closed_deals["lead_behaviour_profile"].unique())
print(df_closed_deals["has_company"].unique())
print(df_closed_deals["has_gtin"].unique())
print(df_closed_deals["average_stock"].unique())
print(df_closed_deals["business_type"].unique())

['pet' 'car_accessories' 'home_appliances' 'food_drink' 'health_beauty'
 'computers' 'household_utilities' 'construction_tools_house_garden'
 'toys' 'sports_leisure' 'stationery' 'food_supplement' 'home_decor'
 'bed_bath_table' 'watches' 'fashion_accessories' 'jewerly' 'party'
 'small_appliances' 'audio_video_electronics' 'other' 'bags_backpacks'
 'home_office_furniture' 'music_instruments' 'books' 'baby'
 'air_conditioning' 'phone_mobile' nan 'handcrafted' 'perfume' 'gifts'
 'religious' 'games_consoles']
['online_medium' 'industry' 'online_big' 'online_small' 'offline'
 'online_top' 'online_beginner' 'other' nan]
['cat' 'eagle' nan 'wolf' 'shark' 'cat, wolf' 'eagle, wolf' 'shark, cat'
 'eagle, cat' 'shark, wolf']
[nan True False]
[nan True False]
[nan '20-50' '1-5' '5-20' '200+' '50-200' 'unknown']
['reseller' 'manufacturer' 'other' nan]

In [12]:
# Reemplazamos los valores NaN por 'Sin dato'
df_closed_deals.fillna({'business_segment': 'Sin dato', 'lead_type': 'Sin dato', 'lead_behaviour_profile': 'Sin dato', 
                        'has_company': 'Sin dato' ,'has_gtin': 'Sin dato','average_stock': 'Sin dato',
                        'business_type': 'Sin dato'}, inplace=True)

In [13]:
# Reemplazamos en average_stock los 'unknown' por 'Sin dato'
df_closed_deals['average_stock'].replace('unknown','Sin dato', inplace=True)

In [14]:
# OUTLIERS
#ventas.loc[ventas['declared_monthly_revenue'] < 1000,'declared_monthly_revenue'] = np.nan
#ventas.loc[ventas['declared_monthly_revenue'] > 500000,'declared_monthly_revenue'] = np.nan

In [15]:
df_closed_deals.isnull().sum()

mql_id                             0
seller_id                          0
sdr_id                             0
sr_id                              0
won_date                           0
business_segment                   0
lead_type                          0
lead_behaviour_profile             0
has_company                        0
has_gtin                           0
average_stock                      0
business_type                      0
declared_product_catalog_size    773
declared_monthly_revenue           0
dtype: int64

In [18]:
# Exportamos nuevo dataset
df_closed_deals.to_csv('./Datasets procesados/ETL closed_deals.csv', index=False)